name: Idée
description: Proposer une amélioration
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: Le besoin
      description: Quel problème cette idée résout-elle ?
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: La proposition
